### ISSUE TITLE
Лабораторная работа #2

### ISSUE THREAD

**Issue by Doshinsky** [Doshinsky/Lab-2#1]
Выполнил:
Дощинский Илья Владиславович  ИС-541

Проверил:
@evgeny-p

**Comment by evgeny-p** [comment]
Замечания оставлены в комментариях:

1. https://github.com/Doshinsky/Lab-2/commit/e1103b4a7b24c4993a9e6e972ab87bc3b2b163fe
1. https://github.com/Doshinsky/Lab-2/commit/a4ec0159ec6e9fc29fd4cb084cd613eb3eea53a2
1. https://github.com/Doshinsky/Lab-2/commit/812364198a3eec8f4309a2b114fc50daa1ebd97c

Заголовки коммитов не в императиве. См. [How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/).

Для сдачи работы нужно привести форматирование кода к общепринятому и убрать лишний блок `else`.

**Comment by Doshinsky** [comment]
Убрал блок else в проверке дискриминанта и заменил мнимую табуляцию на пробелы в другом блоке else. Больше не совпадений по формату не вижу.
@evgeny-p

**Comment by evgeny-p** [comment]
Замечание: https://github.com/Doshinsky/Lab-2/commit/21ff32d3cf865c6527dcf1028106af5de1eee940

Еще момент: не для исправления в рамках этой работы, но для порядка. Числа с плавающей точкой в общем случае нельзя сравнивать на строгое равенство. Используют сравнение с некоторой точностью. Также в рамках данной задачи наличие единственного корня определяется не равенством результатов, а значением дискриминанта. И его сравнение с нулем также должно выполняться с некоторой заданной точностью.

**Comment by Doshinsky** [comment]
Удалил лишнюю } и табуляцию. 

Как выглядеть должно тогда данное сравнение?
@evgeny-p

**Comment by evgeny-p** [comment]
Принято. Задачу можно закрывать.

> Как выглядеть должно тогда данное сравнение?

Примерно так:

```c
#include <math.h>
#include <stdio.h>

int equals(double a, double b, double eps) {
	return fabs(a - b) < eps;
}

int main() {
	const double eps = 10e-6;
	
	const double a = 10.0;
	const double b = 10.1;
	const double c = 10.0000001;
	
	printf("%lf == %lf ? %d\n", a, b, equals(a, b, eps));
	printf("%lf == %lf ? %d\n", a, b, equals(a, c, eps));
	
	// if (equals(a, c, eps)) {
	// ...	
	// }
	
	return 0;
}
```
